### ISSUE TITLE
[Bug] 페이지별 접속시 console에 뜨는 오류 수정

### ISSUE THREAD

**Issue by computer98400** [computer98400/DENS#12]
![image](https://user-images.githubusercontent.com/62691610/157674219-583616d6-db4e-4af1-bc4e-54cde6d45d51.png)
-> fill-rule 속성명 변경 fillRule

**Comment by computer98400** [comment]
![image](https://user-images.githubusercontent.com/62691610/157674390-bd3e7cbb-7b98-462e-9b3d-0e4f0bcd7a06.png)
-> class 속성명 변경 className

**Comment by eunseo130** [comment]
확인했습니다!
