### ISSUE TITLE
컴포넌트 삭제 및 구조 변경

### ISSUE THREAD

**Issue by computer98400** [computer98400/DENS#3]
불필요한 컴포넌트 삭제 및 디렉토리 구조 변경

**Comment by Seungkyu-lee** [comment]
BeforeloginComponent 이름 변경 -> BeforePage
    CertiPassword 이름 변경 -> Passwordupdate
    Firstpage 이름 변경 -> Outerpage
    LoginTest 삭제
AfterPage 폴더 생성
    commonComponent 이름변경 -> Default
        Back 이름변경 -> Innerpage
        HeaderBox 삭제
    dashboardComponent 이름변경 -> Dashboard
        Dashboard 이름 변경 ->  main
        Message 이름 변경
        TeamLink 삭제
        TeamLinkBox 이름 변경 -> Quicklink
        TeamList 삭제
        TeamListBox 이름 변경 -> TeamList
    Header 폴더 삭제
        모두 이동 -> Defaultcomponent
    MessagerComponent 이름 변경 -> Messenger
        Message 삭제
        MessageBox 삭제
        MessageRoom 이름 변경 -> Room
        Messagercard 삭제
        Messager 이름 변경 -> List
        TeamInviteModal 이름 변경 -> Invite
        Main 추가하기.    
    ProfileComponent 이름 변경 -> Profile
        모두 Profile 삭제
    SearchComponent 이름 변경 -> Search
        AllList 삭제
        Search 이름 변경 -> Main
        Searchbigbox 삭제
        Searchsmallbox 삭제
        TeamCard 삭제
        UserCard 삭제

**Comment by computer98400** [comment]
`
BeforeloginComponent 이름 변경 -> BeforePage
    CertiPassword 이름 변경 -> Passwordupdate
    Firstpage 이름 변경 -> Outerpage
    LoginTest 삭제
AfterPage 폴더 생성
    commonComponent 이름변경 -> Default
        Back 이름변경 -> Innerpage
        HeaderBox 삭제
    dashboardComponent 이름변경 -> Dashboard
        Dashboard 이름 변경 ->  main
        Message 이름 변경
        TeamLink 삭제
        TeamLinkBox 이름 변경 -> Quicklink
        TeamList 삭제
        TeamListBox 이름 변경 -> TeamList
    Header 폴더 삭제
        모두 이동 -> Defaultcomponent
    MessagerComponent 이름 변경 -> Messenger
        Message 삭제
        MessageBox 삭제
        MessageRoom 이름 변경 -> Room
        Messagercard 삭제
        Messager 이름 변경 -> List
        TeamInviteModal 이름 변경 -> Invite
        Main 추가하기.    
    ProfileComponent 이름 변경 -> Profile
        모두 Profile 삭제
    SearchComponent 이름 변경 -> Search
        AllList 삭제
        Search 이름 변경 -> Main
        Searchbigbox 삭제
        Searchsmallbox 삭제
        TeamCard 삭제
        UserCard 삭제    
`
