### ISSUE TITLE
코드정리

### ISSUE THREAD

**Issue by Ginnyseo2** [computer98400/DENS#7]
Backend 코드 정리 (클린 코드)

**Comment by KimsHouse** [comment]
코드정리 -끄읏-

**Comment by KimsHouse** [comment]
코드 정리 클래스
 -userfeedserviceimpl
-userfeedservice
-teamserviceimpl
-teammemberserviceimpl
-teamfeedserviceimpl
-profileserviceimpl
-jwtserviceimpl
-hashtagalgorithmfilstore
-emailserviceimpl

-delete saltutil
-delete dummyservice
-delete jwtprovider
